### ISSUE TITLE
Check that Firebase is still up and running

### ISSUE THREAD

**Issue by kavinphan** [GTBitsOfGood/gt-scheduler-website#17]
### Description
Joseph said that there should be credits in the account, so just verify that it is operational.

[Notes from Joseph (previous maintainer)](https://www.notion.so/gtbitsofgood/GT-Scheduler-General-Maintenance-16c7435352a84d1aae8dfcdfcc1ece06)

**Comment by luke9kim8** [comment]
Seems to be operational, we were charged $0.01 last month. For comparison, we were charged $0.76 in November, which was when class registration was happening.
