### ISSUE TITLE
Verify that the web crawler can start

### ISSUE THREAD

**Issue by kavinphan** [GTBitsOfGood/gt-scheduler-website#18]
### Description
The web crawler seems to be kicked off whenever a new commit is added, so attempt to verify this by trying to start it.

[Notes from Joseph (previous maintainer)](https://www.notion.so/gtbitsofgood/GT-Scheduler-General-Maintenance-16c7435352a84d1aae8dfcdfcc1ece06)

**Comment by luke9kim8** [comment]
Trying to be scheduled 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/39681900/156827505-8f1d5aa1-453a-4cf0-b397-2c466c4f512b.png">

**Comment by luke9kim8** [comment]
Yup this works fine. Idk what Joseph did to make it work cuz the last commit was Oct 27 2021 but I see the action getting called every 30 min.
https://github.com/gt-scheduler/crawler/actions
