### ISSUE TITLE
Check for broken classroom locations

### ISSUE THREAD

**Issue by kavinphan** [GTBitsOfGood/gt-scheduler-website#19]
### Description
Sometimes classroom locations change throughout the year, so verify that the classroom locations on the map are still valid.

[Notes from Joseph (previous maintainer)](https://www.notion.so/gtbitsofgood/GT-Scheduler-General-Maintenance-16c7435352a84d1aae8dfcdfcc1ece06)

**Comment by its-edmund** [comment]
Current list of missing locations:
760 Spring St NW 235
China, Shanghai
Clough UG Learning Commons 102
Clough UG Learning Commons 123
Clough UG Learning Commons 125
Clough UG Learning Commons 127
Clough UG Learning Commons 129
Clough UG Learning Commons 131
Clough UG Learning Commons 144
Clough UG Learning Commons 146
Clough UG Learning Commons 150
Clough UG Learning Commons 152
Clough UG Learning Commons 250
Clough UG Learning Commons 262
Clough UG Learning Commons 272
Clough UG Learning Commons 278
Clough UG Learning Commons 280
Clough UG Learning Commons 323
Clough UG Learning Commons 325
Clough UG Learning Commons 335
Clough UG Learning Commons 341
Clough UG Learning Commons 346
Clough UG Learning Commons 357
Clough UG Learning Commons 362
Clough UG Learning Commons 372
Clough UG Learning Commons 373
Clough UG Learning Commons 375
Clough UG Learning Commons 382
Clough UG Learning Commons 383
Clough UG Learning Commons 387
Clough UG Learning Commons 423
Clough UG Learning Commons 473
Clough UG Learning Commons 475
Clough UG Learning Commons 481
Clough UG Learning Commons 483
Clough UG Learning Commons 487
Clough UG Learning Commons 571
Clough UG Learning Commons 572
Clough UG Learning Commons 573
Clough UG Learning Commons 575
Clough UG Learning Commons 581
Clough UG Learning Commons 587
Clough UG Learning Commons 589
College of Computing 101
College of Computing 102
College of Computing 103
College of Computing 16
College of Computing 17
College of Computing 18
College of Computing 30
College of Computing 335
College of Computing 337
College of Computing 52
College of Computing 53
D.M. Smith 104
D.M. Smith 105
D.M. Smith 11
D.M. Smith 15
D.M. Smith 203
D.M. Smith 207
D.M. Smith 208
D.M. Smith 303
D.M. Smith 304
East Architecture 104
East Architecture 107
East Architecture 123
East Architecture 207
East Architecture 304
East Architecture 309
Engineering Sci and Mechanics 201
Engineering Sci and Mechanics 202
Engineering Sci and Mechanics 212
Engineering Sci and Mechanics G1
Engineering Sci and Mechanics G2
Engineering Sci and Mechanics G4
Engineering Sci and Mechanics G8
Ford Environmental Sci & Tech 2115
Ford Environmental Sci & Tech 2229
Ford Environmental Sci & Tech L1105
Ford Environmental Sci & Tech L1116
Ford Environmental Sci & Tech L1118
Ford Environmental Sci & Tech L1125
Ford Environmental Sci & Tech L1155
Ford Environmental Sci & Tech L1160
Ford Environmental Sci & Tech L1175
Ford Environmental Sci & Tech L1205
Ford Environmental Sci & Tech L1255
Ford Environmental Sci & Tech L2160
GT Shenzhen
Georgia Tech Lorraine
Howey Physics L1
Howey Physics L2
Howey Physics L3
Howey Physics L4
Howey Physics L5
Howey Physics N210
Howey Physics S104
Howey Physics S105A
Howey Physics S106
Howey Physics S107
Howey Physics S204
Instructional Center 103
Instructional Center 105
Instructional Center 109
Instructional Center 111
Instructional Center 115
Instructional Center 205
Instructional Center 209
Instructional Center 211
Instructional Center 215
J. Erskine Love Manufacturing 183
J. Erskine Love Manufacturing 184
J. Erskine Love Manufacturing 185
J. Erskine Love Manufacturing 299
J. Erskine Love Manufacturing 312
Manufacture Rel Discip Complex 2101
Manufacture Rel Discip Complex 2404
Manufacture Rel Discip Complex 2405
Manufacture Rel Discip Complex 2407
Manufacture Rel Discip Complex 3317
Manufacture Rel Discip Complex 3321
Manufacture Rel Discip Complex 3336
Manufacture Rel Discip Complex 3403
Manufacture Rel Discip Complex 4211
Molecular Sciences and Engr 1201A
Molecular Sciences and Engr 1222
Molecular Sciences and Engr 1224
Molecular Sciences and Engr 1301
Molecular Sciences and Engr 1303
Molecular Sciences and Engr 3201A
Molecular Sciences and Engr G011
Molecular Sciences and Engr G021
See academic dept
TBA
West Architecture 150
West Architecture 258
West Architecture 259
West Architecture 260
West Architecture 261
West Architecture 265
West Architecture 358
West Architecture 359
Whitaker 0209A
Whitaker 0245
Whitaker 0246
Whitaker 0260
Whitaker 1103
Whitaker 1214
Whitaker 1232

Closing for now
